build: finalize support for gcc 4.7, 4.8
this was the missing issue I also mentioned on ML, now I found a solution.
Now gcc 4.6, 4.7 and 4.8 seem to be able to build the codebase.
http://gcc.gnu.org/gcc-4.7/porting_to.html

In instantiation of ‘int t(T) [with T = int]’
  required from here
  error: ‘f’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  note: ‘int f(int)’ declared here, later in the translation unit

To fix, make sure the function f in the code above is declared before first use in function t.